name: garden
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.2.0
  get_it: ^7.2.0
  auto_route: ^3.2.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_svg: ^1.0.1
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  uuid: ^3.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  freezed: ^1.1.0
  auto_route_generator: ^3.2.1
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700